[project]
name = "python-for-pricing-course"
version = "0.1.0"
description = "Learn how to utilise python in your pricing workflows"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mkdocs>=1.6.1",
    "mkdocs-material>=9.6.16",
]
